#!/usr/bin/env ruby
require 'pp'

# ----------------------------------------------------------------------
# Metric Conversions
module MetricSystemForDummies
  def c_to_f
    32.0 + (self * 9.0) / 5.0
  end

  def f_to_c
    (self - 32.0) * 5.0 / 9.0
  end

  def lb_to_kg
    self / 2.2
  end

  def kg_to_lb
    self * 2.2
  end

  def cm_to_in
    self / 2.54
  end

  def in_to_cm
    self * 2.54
  end
end

class Numeric
  include MetricSystemForDummies
end

begin
  # looksee is awesome. Adds gorgeous Object#ls method
  # https://github.com/oggy/looksee
  require 'looksee'
rescue LoadError => e
  $stderr.puts "~/.irbrc:#{__LINE__}: Could not load looksee/shortcuts: looksee gem not present in this gemset"
end

require "~/dotfiles/json_load_file"
