#!/bin/sh
# export EDITOR=`which emacs`
# export GEMEDITOR=~/bin/aquamacs
# export CVSEDITOR=`which emacs`
# export SVN_EDITOR=`which emacs`
export JAVA_HOME='/System/Library/Frameworks/JavaVM.framework/Home'
export JSTESTDRIVER_HOME=~/devel/jsTestDriver/

# Supposedly this can be found in the Developer Tools that came with
# my Mac. That's the theory, at any rate; in practice it's a load of
# dingo's bicycles.
# export ANT_HOME='/Developer/Java/ant'

# Search the ls manpage for "CLICOLOR" and "color designators for an
# explanation of this goodness.

# CLICOLOR: Search "man ls" for "CLICOLOR" and "color designators".
# a: black                                        1.  directory
# b: red                                          2.  symbolic link
# c: green                                        3.  socket
# d: brown                                        4.  pipe
# e: blue                                         5.  executable
# f: magenta                                      6.  block special
# g: cyan                                         7.  character special
# h: light grey                                   8.  executable with setuid bit set
# A: bold black, usually shows up as dark grey    9.  executable with setgid bit set
# B: bold red                                     10. directory writable to others, with sticky bit   
# C: bold green                                   11. directory writable to others, without sticky bit
# D: bold brown, usually shows up as yellow
# E: bold blue
# F: bold magenta
# G: bold cyan
# H: bold light grey; looks like bright white
# x: default foreground or background
# 
# The standard Mac OSX colors are: exfxcxdxbxegedabagacad
#
export CLICOLOR=1
# Standard colors look good on a white background
# export LSCOLORS=exfxcxdxbxegedabagacad

# Swap blue/cyan for better visibility on dark bg
export LSCOLORS=gxfxcxdxbxegedabagacad

# Use less by default b/c search works better. But keep most inifile
# here for tweaking.
#export PAGER="most"
export MOST_INIFILE='/etc/most.rc'

GREP_OPTIONS='--color=auto'
GREP_COLOR='1;32'

# ----------------------------------------------------------------------
# Terminal colours (after installing GNU coreutils)
NM="\[\033[0;38m\]" #means no background and white lines
HI="\[\033[0;37m\]" #change this for letter colors
HII="\[\033[0;31m\]" #change this for letter colors
SI="\[\033[0;33m\]" #this is for the current directory
IN="\[\033[0m\]"


export HISTFILESIZE=10000

source_files() 
{
  local file

  for file in "$@" ; do

    file=${file/\~\//$HOME\/} # Expand ~/

    if [[ -s "${file}" ]] ; then
      source "${file}"
    else
      if [[ ! -e "${file}" ]] ; then
        printf "NOTICE: ${file} does not exist, not loading.\n"
      else 
        true # simply an empty file, no warning necessary.
      fi
    fi
  done

  return 0
}

# Example usage:

source_files ~/.aliases \
  ~/.bash_completions \
  ~/.git-completion.bash \
  ~/.nav \
  ~/.private \
  ~/.rvm/contrib/ps1_functions

# this must come after git-completion.bash has been sourced
complete -o default -o nospace -F _git_checkout go


if command -v ps1_set >/dev/null 2>&1 ; then
    ps1_set --prompt ∫
else
    export PS1="!!! It's \D{%H} O'Clock! Time to install rvm to fix your prompt!\n$ "
fi

export RUBYOPT=rubygems

# DANGER DANGER DANGER - Do not just slap paths in here willy-nilly. If it's a path to something outside of ~, it should probably go in /etc/paths.d!
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# put MY bin first, THEN homebrew, THEN ports.
export PATH=~/bin:~/scratchbin:~/private_bin:/bin:/usr/local/bin:/usr/local/sbin:$PATH:/usr/local/mysql/bin
export MANPATH=/opt/local/share/man:$MANPATH

# Android SDK
export ANDROID_SDK_ROOT=/usr/local/Cellar/android-sdk/r7

# export MAGLEV_OPTS='-MlogSexp -d -q'
# export MAGLEV_OPTS='-MtraceLoad -MtraceGlobals -d -q'
# export MAGLEV_OPTS='-d -q'
export MAGLEV_HOME='/Users/dbrady/devel/maglev'
export PATH=$PATH:$MAGLEV_HOME/bin

# # RVM
[[ -s "/Users/dbrady/.rvm/scripts/rvm" ]] && source "/Users/dbrady/.rvm/scripts/rvm"  # This loads RVM into a shell session.
rvm default 1.9.2




# giles was here
alias x="exit"
alias X="exit"

