#!/bin/sh
pushd ~
if [ $IS_DOCKER_LOCAL == "1" ]; then
    ln -s ~/dotfiles/dotbash_profile .bashrc
    ln -s ~/dotfiles/dotnav.docker .nav
else
    ln -s ~/dotfiles/dotbashrc .bashrc
    ln -s ~/dotfiles/dotbash_profile .bash_profile
    ln -s ~/dotfiles/dotnav .nav
fi

ln -s ~/dotfiles/bash_completions .bash_completions
ln -s ~/dotfiles/dotaliases .aliases
ln -s ~/dotfiles/dotvimrc .vimrc
ln -s ~/dotfiles/dotirbrc .irbrc
ln -s ~/dotfiles/git-completion.bash .git-completion.bash
ln -s ~/dotfiles/dotgitignore .gitignore

echo "# dotprivate - This is your .private file. It generated by setup.sh\nand does not live in git." > ~/dotfiles/dotprivate
echo "# dotprivate - This is your .private file. It is autogenerated by\nsetup.sh and does not live in git." > ~/dotfiles/dotprivate
ln -s ~/dotfiles/dotprivate .private


ln -s dotfiles/ps1_functions .ps1_functions
ln -s dotfiles/dotvpn .vpn
popd
